In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Rahul" , "Harshita","Sharadha"],
    "CGPA" : [9.5 , 7.5 , 8.5]
}
df = pd.DataFrame(info)

print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2  Sharadha   8.5

In [3]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2  Sharadha   8.5

In [10]:
#series in pandas
s = pd.Series([1,3,4,2,5])
print(s)
print(type(s))

#index access
print(s[0])

0    1
1    3
2    4
3    2
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [18]:
st = pd.Series([23 , 43, 52] , index = ["Adam" ,"Eve" ,"Bob" ])
print(st)

print(st["Adam"])
print(st["Bob"])

print(s.index)
print(st[0])

Adam    23
Eve     43
Bob     52
dtype: int64
23
52
RangeIndex(start=0, stop=5, step=1)
23

/var/folders/1c/29w4nj612ns_rgx1ljtbvlnh0000gn/T/ipykernel_4459/2596359625.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(st[0])

In [28]:
#Series Properties

In [27]:
st  = pd.Series([1,21,0,10,4])
s2  = pd.Series([12,21,20,30,40])
print(st + s2)

st[0] = 100
changed_st=  st.drop(0)

print(st)
print(changed_st)

0    13
1    42
2    20
3    40
4    44
dtype: int64
0    100
1     21
2      0
3     10
4      4
dtype: int64
1    21
2     0
3    10
4     4
dtype: int64

In [32]:
#DATA FRAME

info = {
    "Name" : ["avi" ,"water","air"],
    "Age" :  [24 , 21 , 32],
    "GPA"  : [9.5 , 8.6 , 7.3]
}
df = pd.DataFrame(info)
print(df , type(df))

print(df.index)
print(df.columns)

    Name  Age  GPA
0    avi   24  9.5
1  water   21  8.6
2    air   32  7.3 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [39]:
df = pd.DataFrame([["Adam",23] ,["Bob" , 23] , ["Eve", 23]], columns = ["Name", "Age"])
df

   Name  Age
0  Adam   23
1   Bob   23
2   Eve   23

In [47]:
import numpy as np
np_arr = np.array([[1,2,3] ,[4,5,6]])
df = pd.DataFrame(np_arr , columns = ["A" , "B" , "C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [48]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df , type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [50]:
# json data
df = pd.read_json("employee_data.json")
print(df , type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [51]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [ ]:
#Methods

df.head() #starting 5 rows
df.tail(3) #trailing 5 values , if number provided then, that numner of rows 

df.sample() # any random saple row 

df.info()
df.shape  # 10,5

AQI dataset practice from kaggle

In [69]:
#AQi dataset 

df = pd.read_csv("globalAirQuality.csv")
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [83]:
#selecting data

#column 
df[["city" , "aqi"]]

#rows
df.loc[0] #first row data 
df.loc[0:2] # both the mentioned indexs are included

df.iloc[2] #2nd index data
df.iloc[0:2] #last mentioned index not inculded

#cells - row and col combination
df.loc[0:2,["city", "aqi"]]

df.columns
#FOR iloc you only need to give the numeric input as it is based on indexe

df.iloc[0:2 ,[ 2,11]]


#we generally get the view of what we search not a copy , so if we want to keep teh data unchanged so use .copy() fxn

       city  aqi
0  New York  108
1  New York   90

In [91]:
#Filtering of data

df [(df["aqi"] > 100)  & (df["temperature"] >37)]

#chaining 
df[df["aqi"] > 200] [["city" ,"aqi"]]

           city  aqi
745      London  214
8941      Osaka  204
12956  Auckland  225
14555    Manila  206
17458  Helsinki  202
17529  Helsinki  231
17815    Zurich  203

In [99]:
#query method

df.query("aqi > 100 & temperature > 30") #within query write as much as you want to write 
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

Cleaning data

In [119]:
#cleaning data - handle missing data
df = pd.read_csv("raw_data.csv")
df.isnull() # to detect where is null values

df.isnull().sum() #return the number of missing values 

df.dropna()
df.dropna(axis = 1)

df.fillna(0)

age_mean= df["age"].mean()

clean_data = df.copy() #dont change the original data
clean_data["age"].fillna(age_mean)
df.ffill() #fills with the previous data
df.bfill() #fills with the upcomming data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [123]:
#Handle duplicates

df[["country","gender"]].duplicated()
df2 = df.copy()

df.drop_duplicates(inplace = True)

In [133]:
#Data types

df.dtypes

df2 = df.copy()
df2 = df2.fillna(0) #first fill the empty 
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [134]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [137]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [138]:
date_str =  pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtype)

numpy.dtypes.DateTime64DType

In [146]:
#Handle string 

df["gender"].str.capitalize() #ther are also other options look in the copy

df["name"].str.split(" ") #split the names on the basis of " "

df["country"].str.contains("india" , case =False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object